### ISSUE TITLE
Use modification date of input vodsl as lastModified of output xml

### ISSUE THREAD

**Issue by hugobuddel** [pahjbo/vodsl#11]
Running vodslparser on the same vodsl file twice will give two different xml files because the `lastModified` attribute is set to the current time.

This prevents deterministic builds of the xml files. That is, each run will create different files, e.g. in continuous integration. This could be resolved by using the modification date of the input file as the `lastModified` of the output XML. Another option would be to allow manual specification of the `lastModified` attribute.

This is a minor issue. It is easy to work around it by replacing the `lastModified` automatically after creation.

**Comment by pahjbo** [comment]
I have modified this to behave as you suggested if you pull and rebuild
