### ISSUE TITLE
cannot get GUI to work

### ISSUE THREAD

**Issue by hugobuddel** [pahjbo/vodsl#15]
I cannot get the GUI to work. This seems to be a problem with my FXDiagrams installation, but I don't know how to start troubleshooting this. Any help would be appreciated.

First screenshot shows the context menu. It has "Show in FXDiagram as ..." in there.
![fxdiagram1](https://user-images.githubusercontent.com/1306453/58536592-57b39880-81f1-11e9-900d-3ffcb9b84250.png)

Second screenshot shows me hovering over that option in the menu. Mouse cursor not screenshotted. An empty submenu pops up, of which the corner is just visible on the right side of the screenshot, on the top right corner of the blue selection. The "Show in FXDiagram as" is greyed out.
![fxdiagram2](https://user-images.githubusercontent.com/1306453/58536593-584c2f00-81f1-11e9-9e26-ba10369824cb.png)

Third screenshot shows the context menu again. The "Show in FXDiagram as" option is now gone.
![fxdiagram3](https://user-images.githubusercontent.com/1306453/58536595-584c2f00-81f1-11e9-822b-3f33d9165dc9.png)

So it seems that the FXDiagram plugin crashes or so when trying to fill the "as ..." submenu, and is subsequently inactive.

**Comment by pahjbo** [comment]
I suspect that it will be to do with the availability of JavaFX to the eclipse runtime - without doing too much investigating it might be possible to get it to run by installing efxclipse https://www.eclipse.org/efxclipse/install.html which should hopefully configure JavaFX properly - although again I suspect that this might only be "easy" for Java 8 - so you might want to check that your eclipse is running under java 8 (look for for "installation details" in the dialogue box launched from "about eclipse" menu)

**Comment by hugobuddel** [comment]
Seems to be running with OpenJDK 1.8 indeed. So would be worthwhile to try to use real Java. I'll try and keep you updated.

**Comment by pahjbo** [comment]
hopefully the availability of the pre-built components (see #5 ) that are available for Java 11+ and and eclipse 2021-3 mean that people can run the vodsl editor easily again
