### ISSUE TITLE
.classpath and .project files seem to be missing

### ISSUE THREAD

**Issue by hugobuddel** [pahjbo/vodsl#6]
I'm trying to build the VODSL plugins from source, since the compiled versions are not available (#5), but so far no success.

The closest I got was to import an XText project from the local git repository. This lead to several problems, in particular I got this error:
> Please put bundle org.eclipse.emf.mwe2.launch on your project's classpath.

This is similar as described on this stackoverflow question: https://stackoverflow.com/questions/22556567/how-to-import-an-xtext-project-from-git-in-eclipse

> In your project (by looking at the screenshot) it seems the .project and .classpath files of the projects were not committed into the repository. These files are used by Eclipse to understand which builders to add, what are the source folders, etc.

And indeed these .classpath files (as well as the .project files and .settings directories) are not included in the repository. Could you add these files @pahjbo ?

I'll now try to recreate the project following the 15 minute Xtext tutorial. This will create the missing files.

**Comment by pahjbo** [comment]
you should be able to build purely from the command line with 

`mvn install`

but that is not working at the moment because of a missing dependency. The .project and .classpath files often contain some local configuration that can cause problems  - I will check and see if it is "safe" to add these in the case

**Comment by hugobuddel** [comment]
Hmm, can imagine that there is some local configuration in those files.

But I've no clue how to tell Eclipse where it should find the libraries it needs. So any information on how to do that would be appreciated.
